/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ptidej_panama_jni_Main */

#ifndef _Included_net_ptidej_panama_jni_Main
#define _Included_net_ptidej_panama_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ptidej_panama_jni_Main
 * Method:    stringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_ptidej_panama_jni_Main_stringLength
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
